name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux:
    name: Build and Test on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependencies
        run: python3 -m pip install meson~=1.2.2 ninja~=1.11.1

      - name: Setup build with Meson
        run: meson setup build

      - name: Build with Meson
        run: meson compile -C build

      - name: Test with Meson
        run: meson test -C build

  macos:
    name: Build and Test on macOS
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependencies
        run: python3 -m pip install meson~=1.2.2 ninja~=1.11.1

      - name: Setup build with Meson
        run: meson setup build

      - name: Build with Meson
        run: meson compile -C build

      - name: Test with Meson
        run: meson test -C build

  windows:
    strategy:
      matrix:
        shell: [bash, pwsh]

    name: Build and Test on Windows (${{ matrix.shell }})
    runs-on: windows-latest

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependencies
        run: python -m pip install meson~=1.2.2 ninja~=1.11.1

      - name: Setup build with Meson
        run: meson setup build

      - name: Build with Meson
        run: meson compile -C build

      - name: Test with Meson
        run: meson test -C build

